### ISSUE TITLE
SPI interface

### ISSUE THREAD

**Issue by nleve** [rockwood/exbee#2]
# Feature request

Using SPI to communicate with an XBee would free up the UART for other things, on a RPi for instance. Wondering if that would be better to add in exbee itself, or to include exbee as a dependency in a new project that handles SPI.

My thought is to do this with [elixir_ale](https://github.com/fhunleth/elixir_ale).

**Comment by rockwood** [comment]
@liberza Thanks for reaching out. I'm glad you're interested!

In theory, supporting SPI should be as easy as supplying an alternative adapter that fulfills the [`Exbee.Adapter`](https://hexdocs.pm/exbee/Exbee.Adapter.html#content) behavior. From there, you can use it with `Exbee.start_link(adapter: MySpiAdapter)`. If you can get that working, I'd be happy to merge it as an official adapter.

**Comment by rockwood** [comment]
Closing for now
